language: perl
sudo: false
branches:
  except:
    - /issue\d+/
perl:
  - 5.20.3
  - 5.22.3
  - 5.24.2
  - 5.26.1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - export AUTOMATED_TESTING=1 HARNESS_TIMER=1 AUTHOR_TESTING=0 RELEASE_TESTING=0
  - cpanm --notest Crypt::OpenSSL::Guess
  - cpanm --notest Crypt::OpenSSL::Random
  - cpanm --installdeps --notest .


